In [1]:
import pandas as pd
from operator import itemgetter
import ast

df = pd.read_csv('../data/category_predictions.csv')

In [2]:
places = pd.read_csv('../data/place_df.csv')
places = places[places['country_conf']>0.8]
places = places[pd.notnull(places["geo"])]
def extract_geo(df,l):
    return zip(*[itemgetter(*l)(ast.literal_eval(x.replace("nan",'""'))) for x in places.geo])
places['lat'], places['lon'], places['feature_code'], places["geonameid"], places["place_name"], places["feature_class"] = extract_geo(
    places, 
    ["lat","lon","feature_code","geonameid","place_name","feature_class"]
)

places = places[places['country_conf']>0.8]
places = places[pd.notnull(places["geo"])]

In [3]:
geocolumns = ["feature_code","lat","lon","place_name","feature_class","geonameid"]
places.loc[places["word"]=="Pakistan", geocolumns]=["PCLI",30,70,"Islamic Republic of Pakistan","A",1168579]
places.loc[places["word"]=="Colombia", geocolumns]=["PCLI",4,-73.25,"Colombia","A",3686110]
places.loc[places["word"]=="Argentina", geocolumns]=["PCLI",-34,-64,"Argentine Republic","A",3865483]
places.loc[places["word"]=="Sahara", geocolumns] = ["DSRT", 26, 13, "Sahara", "T", 2212709]
places.loc[places["word"]=="Alps",geocolumns] = ["MTS", 46.41667, 10, "Alps", "T", 2661786]
places.loc[places["word"]=="Mediterranean Sea",geocolumns] = ["SEA", 35, 20, "Mediterranean Sea", "T", 2661786]
places.loc[places["word"]=="MEDITERRANEAN",geocolumns] = ["SEA", 35, 20, "Mediterranean Sea", "T", 2661786]
places.loc[places["word"]=="East China",geocolumns] = ["PCLI", 35, 105, "China", "A", 1814991]
places.loc[places["word"]=="South China",geocolumns] = ["PCLI", 35, 105, "China", "A", 1814991]
places.loc[places["word"]=="Great Lakes",geocolumns] = ["LK", 45.68751, -84.43753, "Great Lakes", "H", 4994594]
places.loc[places["word"]=="Catalonia",geocolumns] = ["ADM1", 41.82046, 1.86768, "Catalunya", "A", 3336901]
places.loc[places["word"]=="South Pacific",geocolumns] = ["OCN", -45, -130, "South Pacific Ocean", "H", 4030483]
places.loc[places["word"]=="Gulf Coast",geocolumns] = ["AREA", 29.36901, -95.00565, "Gulf Coast", "L", 7287689]
places.loc[places["word"]=="Hainan Island",geocolumns] = ["ISL", 19.2, 109.7, "Hainan Dao", "T", 1809055]
places.loc[places["word"]=="Red Sea",geocolumns] = ["SEA", 20.26735, 38.53455, "Red Sea", "H", 350155]
places.loc[places["word"]=="Himalayan",geocolumns] = ["MTS", 28,84, "Himalayas", "T", 1252558]
places.loc[places["word"]=="Himalayas",geocolumns] = ["MTS", 28,84, "Himalayas", "T", 1252558]
places.loc[places["word"]=="North America's",geocolumns] = ["CONT", 46.07323, -100.54688, "North America", "L", 6255149]
places.loc[places["word"]=="Atlantic Ocean",geocolumns] = ["OCN", 10, -25, "Atlantic Ocean", "H", 3373405]
places.loc[places["word"]=="Scandinavia",geocolumns] = ["RGN", 63, 12, "Scandinavia", "L", 2614165]
places.loc[places["word"]=="California (USA",geocolumns] = ["ADM1", 37.25022, -119.75126, "California", "A", 5332921]
places.loc[places["word"]=="California, USA",geocolumns] = ["ADM1", 37.25022, -119.75126, "California", "A", 5332921]
places.loc[places["word"]=="North Pacific",geocolumns] = ["OCN", 30, -170, "North Pacific Ocean", "H", 4030875]
places.loc[places["word"]=="Huai",geocolumns] = ["STM", 33.133333, 118.5, "Huai He", "H", 1807690]
places.loc[places["word"]=="Washington, DC",geocolumns] = ["PPLC", 38.89511, -77.03637, "Washington", "P", 4140963]
places.loc[places["word"]=="Messinian",geocolumns] = ["ADM2", 37.25, -21.83333, "Nomos Messinias", "A", 257149]
places.loc[places["word"]=="Ionian Sea",geocolumns] = ["SEA", 39, 19, "Ionian Sea", "H", 2463713]
places.loc[places["word"]=="NYC",geocolumns] = ["PPL", 40.71427, -74.00597, "New York City", "P", 5128581]

places.loc[places["place_name"]=="Central Upper Nile",geocolumns] = ["ADM1", 10, 32.7, "Upper Nile", "A", 381229]


places.loc[places["place_name"]=="Gobolka Woqooyi Galbeed","place_name"] = "Woqooyi Galbeed"

places = places[places["place_name"]!="Pacific County"]
places = places.loc[places["word"]!="B.V."]
places = places[places["word"]!="MMT"]
places = places[places["word"]!="Yellow"]
places = places[places["word"]!="Western North"]
places = places[places["word"]!="colonies"]
places = places[places["word"]!="TN"]
places = places[places["word"]!="NH"]
places = places[places["word"]!="Mn"]
places = places[places["word"]!="Tx"]
places = places[places["word"]!="TX"]
places = places[places["word"]!="Tn"]
places = places[places["word"]!="FL"]
places = places[places["word"]!="Spartina"]
places = places[places["word"]!="Tamarix"]
places = places[places["word"]!="Eurasia"]
places = places[places["word"]!="Phillyrea"]
places = places[places["word"]!="N-15"]
places = places[places["word"]!="LT50"]
places = places[places["word"]!="POSEIDON"]
places = places[places["word"]!="LC50"]
places = places[places["word"]!="El Nio"]
places = places[places["word"]!="La Nia"]
places = places[places["word"]!="Red"]
places = places[places["word"].str.len()>2]

places.lat = places.lat.astype(float)
places.lon = places.lon.astype(float)

places = places.drop_duplicates(["doc_id","word"])

print(places.shape)

places.to_csv("../data/place_df.csv",index=False)
places.to_csv("~/ownCloud/regional-impacts-data/place_df.csv",index=False)

(93088, 13)

In [4]:
places[places["feature_code"]=="HTL"].groupby('place_name').size().sort_values(ascending=False)

place_name
Drakensberg Gardens Golf & Spa Resort                 12
West Asia Hotel Shanghai                               9
Hotel Hd Beach Resort 4* Costa Teguise Lanzarote       9
Jinjiang Inn (North Wenling Road Quanzhou)             9
Hunguest Hotel Platanus                                8
                                                      ..
Inner Mongolia Jinjiang International Hotel            1
Island Vinnies Tropical Beach Cabana                   1
Jin Feng Huang Hai Jing Hotel Sanya City               1
Jinjiang Inn Shanghai East China Normal University     1
20 Degrees Sud                                         1
Length: 402, dtype: int64

In [5]:
places[places["place_name"].str.contains("ittle Washita Site 13 Reservoi")]

,Unnamed: 0,word,spans,country_predicted,country_conf,geo,doc_id,lat,lon,feature_code,geonameid,place_name,feature_class
56578,174094,Little Washita,"[{'start': 265, 'end': 279}]",USA,0.833024,"{'admin1': 'Oklahoma', 'lat': '34.81812', 'lon...",28635,34.81812,-97.99903,RSV,4541470,Little Washita Site 13 Reservoir,H

In [6]:
did = 28635
print(df[df.id==did].content.values[0])
for i, r in places[places["doc_id"]==did].iterrows():
    print(r["word"],r["place_name"],r["feature_code"],r["country_conf"])

We use an integrated, distributed groundwater-surface water-land surface model, ParFlow, to analyze integrated watershed response and groundwater-land surface feedbacks in the Little Washita River watershed, located within the southern Great Plains region of North America, under observed and perturbed climate conditions. Basin-scale hydrologic sensitivity to temperature and precipitation perturbations is shown to be greatest under energy-limited (direct runoff) conditions compared to moisture-limited (base flow) conditions. Feedbacks between groundwater depth and the land surface water and energy balance are shown to significantly influence surface fluxes under moisture-limited conditions, with differences in latent and sensible heat flux between areas of shallow and deep groundwater depth exceeding 75 W/m(2) under strongly energy-limited conditions. The influence of groundwater feedbacks on sensitivity of surface fluxes to changing climate conditions is shown to depend on changes in both moisture and energy availability over the watershed. Results demonstrate that hydrologic sensitivity to climate change depends on feedbacks between groundwater, overland flow, and the land surface water and energy balance. Results suggest not only that local and watershed response to global climate change depends on groundwater feedbacks but that the magnitude and seasonality of these feedbacks is sensitive to changes in climate.
Little Washita Little Washita Site 13 Reservoir RSV 0.8330239653587341

In [7]:
places.head()

,Unnamed: 0,word,spans,country_predicted,country_conf,geo,doc_id,lat,lon,feature_code,geonameid,place_name,feature_class
0,0,United States,"[{'start': 427, 'end': 440}]",USA,0.999811,"{'admin1': 'NA', 'lat': '39.76', 'lon': '-98.5...",3305893,39.76,-98.5,PCLI,6252001,United States,A
1,3,India,"[{'start': 140, 'end': 145}]",IND,0.999398,"{'admin1': 'NA', 'lat': '22', 'lon': '79', 'co...",1477550,22.00,79.0,PCLI,1269750,Republic of India,A
2,4,Russia,"[{'start': 697, 'end': 703}]",RUS,0.999401,"{'admin1': 'NA', 'lat': '60', 'lon': '100', 'c...",1477550,60.00,100.0,PCLI,2017370,Russian Federation,A
3,5,Pakistan,"[{'start': 763, 'end': 771}]",PAK,0.989610,"{'admin1': 'Punjab', 'lat': '31.4706', 'lon': ...",1477550,30.00,70.0,PCLI,1168579,Islamic Republic of Pakistan,A
4,8,Cameroon,"[{'start': 213, 'end': 221}]",CMR,0.999931,"{'admin1': 'NA', 'lat': '6', 'lon': '12.5', 'c...",1336166,6.00,12.5,PCLI,2233387,Republic of Cameroon,A

In [8]:
import pycountry_convert as pc
def get_cont(x):
    continents = {
        'NA': 'North America',
        'SA': 'South America', 
        'AS': 'Asia',
        'OC': 'Oceania',
        'AF': 'Africa',
        'EU': 'Europe'
    }
    try:
        return continents[pc.country_alpha2_to_continent_code(pc.country_alpha3_to_country_alpha2(x['country_predicted']))]
    except:
        return None
places['continent'] = places.apply(lambda x: get_cont(x), axis=1)
other_country_continents = [
    ("ESH","Africa"),
    ("TLS","Oceania"),
    ("XKX","Europe")
    
]
for country,continent in other_country_continents:
    places.loc[places['country_predicted']==country,"continent"] = continent

places.head()

,Unnamed: 0,word,spans,country_predicted,country_conf,geo,doc_id,lat,lon,feature_code,geonameid,place_name,feature_class,continent
0,0,United States,"[{'start': 427, 'end': 440}]",USA,0.999811,"{'admin1': 'NA', 'lat': '39.76', 'lon': '-98.5...",3305893,39.76,-98.5,PCLI,6252001,United States,A,North America
1,3,India,"[{'start': 140, 'end': 145}]",IND,0.999398,"{'admin1': 'NA', 'lat': '22', 'lon': '79', 'co...",1477550,22.00,79.0,PCLI,1269750,Republic of India,A,Asia
2,4,Russia,"[{'start': 697, 'end': 703}]",RUS,0.999401,"{'admin1': 'NA', 'lat': '60', 'lon': '100', 'c...",1477550,60.00,100.0,PCLI,2017370,Russian Federation,A,Europe
3,5,Pakistan,"[{'start': 763, 'end': 771}]",PAK,0.989610,"{'admin1': 'Punjab', 'lat': '31.4706', 'lon': ...",1477550,30.00,70.0,PCLI,1168579,Islamic Republic of Pakistan,A,Asia
4,8,Cameroon,"[{'start': 213, 'end': 221}]",CMR,0.999931,"{'admin1': 'NA', 'lat': '6', 'lon': '12.5', 'c...",1336166,6.00,12.5,PCLI,2233387,Republic of Cameroon,A,Africa

In [11]:
doc_continents = places[["doc_id","continent"]]
print(doc_continents.shape)
doc_continents = doc_continents.drop_duplicates(["doc_id","continent"])
print(doc_continents.shape)
doc_continents.to_csv('../data/doc_continents.csv',index=False)

(93088, 2)
(57535, 2)